pull_request_rules:
  - name: merge scala-steward PRs
    conditions:
      - 'author=fgrutsch'
      - 'head~=update\/.+'
      - 'status-success~=Build and Test \(ubuntu-latest, 2\.\d{1,2}\.\d{1,2}, temurin@11\)'
      - 'status-success~=Build and Test \(ubuntu-latest, 3\.\d{1,2}\.\d{1,2}, temurin@11\)'
      - 'status-success~=Build and Test \(ubuntu-latest, 2\.\d{1,2}\.\d{1,2}, temurin@17\)'
      - 'status-success~=Build and Test \(ubuntu-latest, 3\.\d{1,2}\.\d{1,2}, temurin@17\)'
    actions:
      merge:
        method: squash