addSbtPlugin("ch.epfl.scala"         % "sbt-scalafix"       % "0.10.4")
addSbtPlugin("com.github.sbt"        % "sbt-github-actions" % "0.15.0")
addSbtPlugin("com.github.sbt"        % "sbt-ci-release"     % "1.5.12")
addSbtPlugin("com.lightbend.paradox" % "sbt-paradox"        % "0.10.3")
addSbtPlugin("de.heikoseeberger"     % "sbt-header"         % "5.9.0")
addSbtPlugin("org.scalameta"         % "sbt-scalafmt"       % "2.5.0")
addSbtPlugin("org.scoverage"         % "sbt-scoverage"      % "2.0.7")
